[tool.poetry]
name = "rental_ad_schema"
version = "0.0.1"
description = ""
authors = ["Adam Bako"]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
