[tool.poetry]
name = "{{scraper_snake_case_name}}"
version = "0.0.1"
description = ""
authors = ["Adam Bako"]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
